### ISSUE TITLE
Hello Sir

### ISSUE THREAD

**Issue by Imnotkaihorton123abc** [LauchyTheProgrammer/ITWebsite#3]
I am leaving this educated criticism because I looked at your I.T assignment and these are my thoughts on what was wrong with it and how you can improve it
1. It is trash and give up on this website
2. Your name is bad because it should be spelt: Lochnes Monstah and his phat addiction to gems
3. Both of your Clash of Clans bases are horrid give up on that game aswell.
I hope you enjoyed my feed back and take all of it into consideration while making your "ITWebsite"

**Comment by LauchyTheProgrammer** [comment]
Fck ur feedback, it is shit.
